2025-06-21 22:37:01,414 [INFO    ] Request: GET http://127.0.0.1:8000/
2025-06-21 22:37:01,422 [INFO    ] Response status: 404
2025-06-21 22:37:03,273 [INFO    ] Request: GET http://127.0.0.1:8000/favicon.ico
2025-06-21 22:37:03,305 [INFO    ] Response status: 404
2025-06-21 22:37:07,500 [INFO    ] Request: GET http://127.0.0.1:8000/docs
2025-06-21 22:37:07,501 [INFO    ] Response status: 200
2025-06-21 22:37:08,211 [INFO    ] Request: GET http://127.0.0.1:8000/openapi.json
2025-06-21 22:37:08,224 [INFO    ] Response status: 200
2025-06-21 22:37:16,931 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/test
2025-06-21 22:37:16,933 [INFO    ] Response status: 200
2025-06-21 22:37:28,474 [INFO    ] Request: POST http://127.0.0.1:8000/api/user/create_user
2025-06-21 22:37:28,700 [INFO    ] Response status: 200
2025-06-21 22:37:41,044 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:37:41,049 [INFO    ] Response status: 200
2025-06-21 22:38:46,996 [INFO    ] Request: GET http://127.0.0.1:8000/docs
2025-06-21 22:38:46,996 [INFO    ] Response status: 200
2025-06-21 22:38:47,607 [INFO    ] Request: GET http://127.0.0.1:8000/openapi.json
2025-06-21 22:38:47,617 [INFO    ] Response status: 200
2025-06-21 22:38:52,491 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:38:52,496 [ERROR   ] Unexpected exception occurred: NameError - name 'get_user_by_id' is not defined while processing request GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:39:05,965 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:39:06,146 [INFO    ] Response status: 200
2025-06-21 22:42:14,000 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:42:14,691 [ERROR   ] Unexpected exception occurred: DBAPIError - (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: <built-in function id> ('builtin_function_or_method' object cannot be interpreted as an integer)
[SQL: SELECT users.id, users.name, users.surname, users.patronymic, users.datetime_reg, users.dateborn, users.email, users.hashed_password, users.created_at, users.updated_at 
FROM users 
WHERE users.id = $1::INTEGER]
[parameters: (<built-in function id>,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi) while processing request GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:47:49,992 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:47:50,219 [INFO    ] Response status: 200
2025-06-21 22:48:02,727 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:48:02,997 [INFO    ] Response status: 200
2025-06-21 22:48:23,665 [INFO    ] Request: GET http://127.0.0.1:8000/api/user/1
2025-06-21 22:48:23,912 [INFO    ] Response status: 200
